name       : python-xxhash
version    : 1.4.3
release    : 4
source     :
    - https://files.pythonhosted.org/packages/df/02/89b90fd83d5e882697d26b07c0cebc14caa4953d1aeeaee07f777fd33799/xxhash-1.4.3.tar.gz : 8b6b1afe7731d7d9cbb0398b4a811ebb5e6be5c174f72c68abf81f919a435de9
license    : BSD-2-Clause
component  : programming.python
summary    : Python binding for xxHash
description: |
    xxhash is a Python binding for the xxHash library.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - xxhash
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
