name       : python-xxhash
version    : 1.3.0
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/x/xxhash/xxhash-1.3.0.tar.gz : fe21f23a9d05428c75461790b670f2bf15f50a632d6c171a7e7b588269c619e6
license    : BSD-2-Clause
component  : programming.python
summary    : Python binding for xxHash
description: |
    xxhash is a Python binding for the xxHash library.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - xxhash
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
