name       : python-xxhash
version    : 2.0.2
release    : 7
source     :
    - https://github.com/ifduyue/python-xxhash/archive/refs/tags/v2.0.2.tar.gz : 14d93743bb6336fb6f89574f1ac7810b6c38e02ecb2354584d9b3dd8ad50f2b2
license    : BSD-2-Clause
component  : programming.python
summary    : Python binding for xxHash
description: |
    xxhash is a Python binding for the xxHash library.
builddeps  :
    - pkgconfig(libxxhash)
    - pkgconfig(python3)
rundeps    :
    - xxhash
environment: |
    export XXHASH_LINK_SO=1
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
