name       : python-xxhash
version    : 2.0.0
release    : 6
source     :
    - https://github.com/ifduyue/python-xxhash/releases/download/v2.0.0/xxhash-2.0.0.tar.gz : 58ca818554c1476fa1456f6cd4b87002e2294f09baf0f81e5a2a4968e62c423c
license    : BSD-2-Clause
component  : programming.python
summary    : Python binding for xxHash
description: |
    xxhash is a Python binding for the xxHash library.
builddeps  :
    - pkgconfig(libxxhash)
    - pkgconfig(python3)
rundeps    :
    - xxhash
environment: |
    export XXHASH_LINK_SO=1
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
